Repository bbta3-bppt/website-worker, pull requests merged in 2021-02, with the labels that each got.

#15 Mengajukan perombakan kode worker
  Cargo.lock
  Cargo.toml
  src/handlers/building.rs
  src/handlers/fetching.rs
  src/handlers/mod.rs
  src/handlers/parsing.rs
  src/helpers/error.rs
  src/helpers/mod.rs
  src/helpers/parse.rs
  src/helpers/process.rs
  src/helpers/text.rs
  src/helpers/utility.rs
  src/main.rs
  src/models/berita.rs
  src/models/error.rs
  src/models/mod.rs
Labels: breaking

#16 update dokumentasi repositori
  README.md
Labels: maintenance

#17 Modifikasi lanjut fungsi-fungsi worker
  .github/workflows/release.yml
  src/handlers/mod.rs
  src/handlers/saving.rs
  src/handlers/starting.rs
  src/helpers/mod.rs
  src/helpers/process.rs
  src/helpers/save.rs
  src/main.rs
  src/models/error.rs
Labels: maintenance

#18 update README
  README.md
Labels: documentation

#20 Uji coba build website worker
  .github/workflows/release.yml
Labels: maintenance

#21 tambah master branche
  .github/workflows/release.yml
Labels: maintenance

#22 uji coba upload assets
  .github/workflows/release.yml
Labels: maintenance

#23 Pemisahan github workflow untuk release dan upload asset
  .github/workflows/release.yml
  .github/workflows/upload.yaml
Labels: maintenance

#25 uji coba membuat .env file action
  .github/workflows/upload.yaml
Labels: maintenance

#26 Menerapkan dotenv
  Cargo.lock
  Cargo.toml
  src/handlers/starting.rs
Labels: maintenance

#27 Hapus field env yang tidak digunakan
  .github/workflows/upload.yaml
Labels: maintenance

#28 Koreksi penamaan release
  .github/workflows/upload.yaml
Labels: maintenance

#29 Koreksi perintan .env file
  .github/workflows/upload.yaml
Labels: maintenance

#30 Minimalisasi ukuran upload asset
  .github/workflows/upload.yaml
Labels: maintenance
